In [15]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import re
from random import randint

In [4]:
file = 'dis_acct_e.csv'
dateRePattern = re.compile('^\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])$')
print(dateRePattern.match('2015-12-31'))

<_sre.SRE_Match object at 0x2163140>

In [5]:
dis_acct_e = pd.concat(pd.read_csv(file, chunksize=1000, date_parser=pd.datetools.to_datetime))

In [6]:
dis_acct_e.head()

,me_dt,acct_id,acct_sub_type,acct_opnd_dt,acct_opng_brnch_id,acct_sts,cust_id,prod_id,fincg_type_cd,tenor,...,inlien_ind,cury_cd,bal_outst_amt,avg_bal_out_globl_amt,avg_bal_out_globl_amt_cr,avg_bal_out_globl_amt_dr,fund_cr_amt,fund_chrg_amt,inlien_amt,no_of_time_renewed
0,2015-12-31,18124905,CURRENT ACCOUNT/OVERDRAFT,2013-07-18,3426827,CLOSE,11716809,6302,191,NaN,...,N,MYR,16.289508,15.649508,15.969508,24.839508,15.679508,7.129508,16.259508,0
1,2015-12-31,17816466,CURRENT ACCOUNT/OVERDRAFT,2013-04-10,3426532,CLOSE,11503652,6302,191,NaN,...,N,MYR,73659.291778,44321.011778,58990.151778,78314.921778,44385.081778,39729.451778,73595.221778,0
2,2015-12-31,2189400,CURRENT ACCOUNT/OVERDRAFT,2013-11-27,3426268,ACTIVE,116097,5831,111,NaN,...,N,MYR,172067.371356,84835.531356,128451.451356,158898.531356,84934.011356,98102.851356,171968.891356,0
3,2015-12-31,17851353,CURRENT ACCOUNT/OVERDRAFT,2014-07-20,3426565,ACTIVE,12568229,6302,191,NaN,...,N,MYR,1969.166978,1094.726978,1531.946978,1977.716978,1096.206978,1087.656978,1967.686978,0
4,2015-12-31,18208198,CURRENT ACCOUNT/OVERDRAFT,2014-01-22,3426892,DORMANT,12123857,6302,191,NaN,...,N,MYR,44622.457314,24656.457314,34639.457314,44622.457314,24689.557314,24689.557314,44589.357314,0

In [18]:
print(len(dis_acct_e)*0.0001)
print(randint(0, 1000))

114.4394
840

In [31]:
def detectDates(scaleFactor=0.0001):
    numTries = len(dis_acct_e) * scaleFactor
    lenData = len(dis_acct_e)
    for x in dis_acct_e.columns:
        for x in range(int(numTries)):
            try:
                print(int(dis_acct_e[x].iloc[randint(0, lenData)][0]))
                if isinstance(int(dis_acct_e[x].iloc[randint(0, lenData)][0]), int):
                    print(dateRePattern.match(dis_acct_e[x].iloc[1]))
#                     print(dis_acct_e[x].iloc[1])
                else:
                    print('reached here')
            except:
                    continue
                    print(dis_acct_e[x].iloc[1])
                    print('false.......')
detectDates()

In [2]:
dis_acct_e_nonInt = dis_acct_e.set_index('acct_id').select_dtypes(exclude=['floating', 'int',])
dis_acct_e_nonInt.head()

NameError: name 'dis_acct_e' is not defined

In [6]:
dis_acct_e['me_dt'] = pd.to_datetime(dis_acct_e['me_dt'])
dis_acct_e['acct_opnd_dt'] = pd.to_datetime(dis_acct_e['acct_opnd_dt'])
dis_acct_e['cert_iss_dt'] = pd.to_datetime(dis_acct_e['cert_iss_dt'])
dis_acct_e['dep_maturity_dt'] = pd.to_datetime(dis_acct_e['dep_maturity_dt'])
print(dis_acct_e['me_dt'].dtype)
dis_acct_e_nonInt1 = dis_acct_e
print(dis_acct_e_nonInt1['me_dt'].dtype)

datetime64[ns]
datetime64[ns]

In [7]:
dis_acct_e_nonInt1 = dis_acct_e_nonInt1.select_dtypes(exclude=['datetime64[ns]'])

In [8]:
dis_acct_e_nonInt1.head()

,acct_id,acct_sub_type,acct_opng_brnch_id,acct_sts,cust_id,prod_id,fincg_type_cd,tenor,tenor_uom,remain_term,...,inlien_ind,cury_cd,bal_outst_amt,avg_bal_out_globl_amt,avg_bal_out_globl_amt_cr,avg_bal_out_globl_amt_dr,fund_cr_amt,fund_chrg_amt,inlien_amt,no_of_time_renewed
0,18124905,CURRENT ACCOUNT/OVERDRAFT,3426827,CLOSE,11716809,6302,191,NaN,NaN,0,...,N,MYR,16.289508,15.649508,15.969508,24.839508,15.679508,7.129508,16.259508,0
1,17816466,CURRENT ACCOUNT/OVERDRAFT,3426532,CLOSE,11503652,6302,191,NaN,NaN,0,...,N,MYR,73659.291778,44321.011778,58990.151778,78314.921778,44385.081778,39729.451778,73595.221778,0
2,2189400,CURRENT ACCOUNT/OVERDRAFT,3426268,ACTIVE,116097,5831,111,NaN,NaN,0,...,N,MYR,172067.371356,84835.531356,128451.451356,158898.531356,84934.011356,98102.851356,171968.891356,0
3,17851353,CURRENT ACCOUNT/OVERDRAFT,3426565,ACTIVE,12568229,6302,191,NaN,NaN,0,...,N,MYR,1969.166978,1094.726978,1531.946978,1977.716978,1096.206978,1087.656978,1967.686978,0
4,18208198,CURRENT ACCOUNT/OVERDRAFT,3426892,DORMANT,12123857,6302,191,NaN,NaN,0,...,N,MYR,44622.457314,24656.457314,34639.457314,44622.457314,24689.557314,24689.557314,44589.357314,0

In [9]:
dis_acct_e_nonInt1.iloc[:,0:].apply(pd.Series.value_counts)

MemoryError:

               acct_id  acct_sub_type  acct_opng_brnch_id  acct_sts  cust_id  \
0.000000           NaN            NaN                 NaN       NaN      NaN
1.000000           NaN            NaN                 NaN       NaN      NaN
2.000000           NaN            NaN                 NaN       NaN      NaN
3.000000           NaN            NaN                 NaN       NaN      NaN
4.000000           NaN            NaN                 NaN       NaN      NaN
5.000000           NaN            NaN                 NaN       NaN      NaN
6.000000           NaN            NaN                 NaN       NaN      NaN
7.000000           NaN            NaN                 NaN       NaN      NaN
8.000000           NaN            NaN                 NaN       NaN      NaN
9.000000           NaN            NaN                 NaN       NaN      NaN
10.000000          NaN            NaN                 NaN       NaN      NaN
11.000000          NaN            NaN                 NaN       NaN      NaN
12.000000          NaN            NaN                 NaN       NaN      NaN
13.000000          NaN            NaN                 NaN       NaN      NaN
14.000000          NaN            NaN                 NaN       NaN      NaN
15.000000          NaN            NaN                 NaN       NaN      NaN
16.000000          NaN            NaN                 NaN       NaN      NaN
17.000000          NaN            NaN                 NaN       NaN      NaN
18.000000          NaN            NaN                 NaN       NaN      NaN
19.000000          NaN            NaN                 NaN       NaN      NaN
20.000000          NaN            NaN                 NaN       NaN      NaN
21.000000          NaN            NaN                 NaN       NaN      NaN
22.000000          NaN            NaN                 NaN       NaN      NaN
23.000000          NaN            NaN                 NaN       NaN      NaN
24.000000          NaN            NaN                 NaN       NaN      NaN
30.000000          NaN            NaN                 NaN       NaN      NaN
31.000000          NaN            NaN                 NaN       NaN      NaN
32.000000          NaN            NaN                 NaN       NaN      NaN
36.000000          NaN            NaN                 NaN       NaN      NaN
57.000000          NaN            NaN                 NaN       NaN      NaN
...                ...            ...                 ...       ...      ...
2124.751823        NaN            NaN                 NaN       NaN      NaN
5919.439189        NaN            NaN                 NaN       NaN      NaN
2104.205919        NaN            NaN                 NaN       NaN      NaN
32426.647329       NaN            NaN                 NaN       NaN      NaN
3716.369553        NaN            NaN                 NaN       NaN      NaN
3931.738128        NaN            NaN                 NaN       NaN      NaN
10073.844115       NaN            NaN                 NaN       NaN      NaN
417053.353656      NaN            NaN                 NaN       NaN      NaN
14466.026653       NaN            NaN                 NaN       NaN      NaN
22414.092332       NaN            NaN                 NaN       NaN      NaN
48254.590872       NaN            NaN                 NaN       NaN      NaN
18796.240606       NaN            NaN                 NaN       NaN      NaN
38683.074819       NaN            NaN                 NaN       NaN      NaN
10558.663204       NaN            NaN                 NaN       NaN      NaN
156310.486197      NaN            NaN                 NaN       NaN      NaN
221051.923406      NaN            NaN                 NaN       NaN      NaN
952.188909         NaN            NaN                 NaN       NaN      NaN
5466.965097        NaN            NaN                 NaN       NaN      NaN
26.000000          NaN            NaN                 NaN       NaN      NaN
27.000000          NaN            NaN                 NaN       NaN      NaN
25.000000          NaN            NaN                 NaN       NaN      NaN
29.000000          NaN            NaN                 NaN       NaN      NaN
28.000000          NaN            NaN                 NaN       NaN      NaN
33.000000          NaN            NaN                 NaN       NaN      NaN
34.000000          NaN            NaN                 NaN       NaN      NaN
35.000000          NaN            NaN                 NaN       NaN      NaN
37.000000          NaN            NaN                 NaN       NaN      NaN
38.000000          NaN            NaN                 NaN       NaN      NaN
49.000000          NaN            NaN                 NaN       NaN      NaN
48.000000          NaN            NaN                 NaN       NaN      NaN

               prod_id  fincg_type_cd    tenor  tenor_uom  remain_term  \
0.000000           NaN            NaN      NaN        NaN    1006248.0
1.000000           NaN            NaN  47714.0        NaN       2180.0
2.000000           NaN            NaN   4706.0        NaN       5210.0
3.000000           NaN            NaN  19520.0        NaN       4874.0
4.000000           NaN            NaN   1006.0        NaN       5040.0
5.000000           NaN            NaN   3882.0        NaN      10732.0
6.000000           NaN            NaN   9564.0        NaN      13882.0
7.000000           NaN            NaN     16.0        NaN      14156.0
8.000000           NaN            NaN    100.0        NaN      14742.0
9.000000           NaN            NaN    912.0        NaN      14872.0
10.000000          NaN            NaN     12.0        NaN      14344.0
11.000000          NaN            NaN     12.0        NaN      10412.0
12.000000          NaN            NaN  50536.0        NaN       7534.0
13.000000          NaN            NaN      NaN        NaN       3250.0
14.000000          NaN            NaN      NaN        NaN       2900.0
15.000000          NaN            NaN      NaN        NaN       2684.0
16.000000          NaN            NaN      NaN        NaN       2692.0
17.000000          NaN            NaN      NaN        NaN       2490.0
18.000000          NaN            NaN      NaN        NaN       2184.0
19.000000          NaN            NaN      NaN        NaN       1730.0
20.000000          NaN            NaN      NaN        NaN       1260.0
21.000000          NaN            NaN      NaN        NaN        764.0
22.000000          NaN            NaN      NaN        NaN        180.0
23.000000          NaN            NaN      NaN        NaN          2.0
24.000000          NaN            NaN     76.0        NaN          2.0
30.000000          NaN            NaN      NaN        NaN          2.0
31.000000          NaN            NaN      NaN        NaN          2.0
32.000000          NaN            NaN      NaN        NaN          2.0
36.000000          NaN            NaN     78.0        NaN          NaN
57.000000          NaN            NaN      NaN        NaN          6.0
...                ...            ...      ...        ...          ...
2124.751823        NaN            NaN      NaN        NaN          NaN
5919.439189        NaN            NaN      NaN        NaN          NaN
2104.205919        NaN            NaN      NaN        NaN          NaN
32426.647329       NaN            NaN      NaN        NaN          NaN
3716.369553        NaN            NaN      NaN        NaN          NaN
3931.738128        NaN            NaN      NaN        NaN          NaN
10073.844115       NaN            NaN      NaN        NaN          NaN
417053.353656      NaN            NaN      NaN        NaN          NaN
14466.026653       NaN            NaN      NaN        NaN          NaN
22414.092332       NaN            NaN      NaN        NaN          NaN
48254.590872       NaN            NaN      NaN        NaN          NaN
18796.240606       NaN            NaN      NaN        NaN          NaN
38683.074819       NaN            NaN      NaN        NaN          NaN
10558.663204       NaN            NaN      NaN        NaN          NaN
156310.486197      NaN            NaN      NaN        NaN          NaN
221051.923406      NaN            NaN      NaN        NaN          NaN
952.188909         NaN            NaN      NaN        NaN          NaN
5466.965097        NaN            NaN      NaN        NaN          NaN
26.000000          NaN            NaN      NaN        NaN          NaN
27.000000          NaN            NaN      NaN        NaN          NaN
25.000000          NaN            NaN      NaN        NaN          NaN
29.000000          NaN            NaN      NaN        NaN          NaN
28.000000          NaN            NaN      NaN        NaN          NaN
33.000000          NaN            NaN      NaN        NaN          NaN
34.000000          NaN            NaN      NaN        NaN          NaN
35.000000          NaN            NaN      NaN        NaN          NaN
37.000000          NaN            NaN      NaN        NaN          NaN
38.000000          NaN            NaN      NaN        NaN          NaN
49.000000          NaN            NaN      NaN        NaN          NaN
48.000000          NaN            NaN      NaN        NaN          NaN

                      ...          inlien_ind  cury_cd  bal_outst_amt  \
0.000000              ...                 NaN      NaN         4738.0
1.000000              ...                 NaN      NaN            NaN
2.000000              ...                 NaN      NaN            NaN
3.000000              ...                 NaN      NaN            NaN
4.000000              ...                 NaN      NaN            NaN
5.000000              ...                 NaN      NaN            NaN
6.000000              ...                 NaN      NaN            NaN
7.000000              ...                 NaN      NaN            NaN
8.000000              ...                 NaN      NaN            NaN
9.000000              ...                 NaN      NaN            NaN
10.000000             ...                 NaN      NaN            NaN
11.000000             ...                 NaN      NaN            NaN
12.000000             ...                 NaN      NaN            NaN
13.000000             ...                 NaN      NaN            NaN
14.000000             ...                 NaN      NaN            NaN
15.000000             ...                 NaN      NaN            NaN
16.000000             ...                 NaN      NaN            NaN
17.000000             ...                 NaN      NaN            NaN
18.000000             ...                 NaN      NaN            NaN
19.000000             ...                 NaN      NaN            NaN
20.000000             ...                 NaN      NaN            NaN
21.000000             ...                 NaN      NaN            NaN
22.000000             ...                 NaN      NaN            NaN
23.000000             ...                 NaN      NaN            NaN
24.000000             ...                 NaN      NaN            NaN
30.000000             ...                 NaN      NaN            NaN
31.000000             ...                 NaN      NaN            NaN
32.000000             ...                 NaN      NaN            NaN
36.000000             ...                 NaN      NaN            NaN
57.000000             ...                 NaN      NaN            NaN
...                   ...                 ...      ...            ...
2124.751823           ...                 NaN      NaN            NaN
5919.439189           ...                 NaN      NaN            NaN
2104.205919           ...                 NaN      NaN            NaN
32426.647329          ...                 NaN      NaN            NaN
3716.369553           ...                 NaN      NaN            NaN
3931.738128           ...                 NaN      NaN            NaN
10073.844115          ...                 NaN      NaN            NaN
417053.353656         ...                 NaN      NaN            NaN
14466.026653          ...                 NaN      NaN            NaN
22414.092332          ...                 NaN      NaN            NaN
48254.590872          ...                 NaN      NaN            NaN
18796.240606          ...                 NaN      NaN            NaN
38683.074819          ...                 NaN      NaN            NaN
10558.663204          ...                 NaN      NaN            NaN
156310.486197         ...                 NaN      NaN            NaN
221051.923406         ...                 NaN      NaN            NaN
952.188909            ...                 NaN      NaN            NaN
5466.965097           ...                 NaN      NaN            NaN
26.000000             ...                 NaN      NaN            NaN
27.000000             ...                 NaN      NaN            NaN
25.000000             ...                 NaN      NaN            NaN
29.000000             ...                 NaN      NaN            NaN
28.000000             ...                 NaN      NaN            NaN
33.000000             ...                 NaN      NaN            NaN
34.000000             ...                 NaN      NaN            NaN
35.000000             ...                 NaN      NaN            NaN
37.000000             ...                 NaN      NaN            NaN
38.000000             ...                 NaN      NaN            NaN
49.000000             ...                 NaN      NaN            NaN
48.000000             ...                 NaN      NaN            NaN

               avg_bal_out_globl_amt  avg_bal_out_globl_amt_cr  \
0.000000                      4738.0                    4738.0
1.000000                         NaN                       NaN
2.000000                         NaN                       NaN
3.000000                         NaN                       NaN
4.000000                         NaN                       NaN
5.000000                         NaN                       NaN
6.000000                         NaN                       NaN
7.000000                         NaN                       NaN
8.000000                         NaN                       NaN
9.000000                         NaN                       NaN
10.000000                        NaN                       NaN
11.000000                        NaN                       NaN
12.000000                        NaN                       NaN
13.000000                        NaN                       NaN
14.000000                        NaN                       NaN
15.000000                        NaN                       NaN
16.000000                        NaN                       NaN
17.000000                        NaN                       NaN
18.000000                        NaN                       NaN
19.000000                        NaN                       NaN
20.000000                        NaN                       NaN
21.000000                        NaN                       NaN
22.000000                        NaN                       NaN
23.000000                        NaN                       NaN
24.000000                        NaN                       NaN
30.000000                        NaN                       NaN
31.000000                        NaN                       NaN
32.000000                        NaN                       NaN
36.000000                        NaN                       NaN
57.000000                        NaN                       NaN
...                              ...                       ...
2124.751823                      NaN                       NaN
5919.439189                      NaN                       NaN
2104.205919                      NaN                       NaN
32426.647329                     NaN                       NaN
3716.369553                      NaN                       NaN
3931.738128                      NaN                       NaN
10073.844115                     NaN                       NaN
417053.353656                    NaN                       NaN
14466.026653                     NaN                       NaN
22414.092332                     NaN                       NaN
48254.590872                     NaN                       NaN
18796.240606                     NaN                       NaN
38683.074819                     NaN                       NaN
10558.663204                     NaN                       NaN
156310.486197                    NaN                       NaN
221051.923406                    NaN                       NaN
952.188909                       NaN                       NaN
5466.965097                      NaN                       NaN
26.000000                        NaN                       NaN
27.000000                        NaN                       NaN
25.000000                        NaN                       NaN
29.000000                        NaN                       NaN
28.000000                        NaN                       NaN
33.000000                        NaN                       NaN
34.000000                        NaN                       NaN
35.000000                        NaN                       NaN
37.000000                        NaN                       NaN
38.000000                        NaN                       NaN
49.000000                        NaN                       NaN
48.000000                        NaN                       NaN

               avg_bal_out_globl_amt_dr  fund_cr_amt  fund_chrg_amt  \
0.000000                         4738.0       4738.0         4738.0
1.000000                            NaN          NaN            NaN
2.000000                            NaN          NaN            NaN
3.000000                            NaN          NaN            NaN
4.000000                            NaN          NaN            NaN
5.000000                            NaN          NaN            NaN
6.000000                            NaN          NaN            NaN
7.000000                            NaN          NaN            NaN
8.000000                            NaN          NaN            NaN
9.000000                            NaN          NaN            NaN
10.000000                           NaN          NaN            NaN
11.000000                           NaN          NaN            NaN
12.000000                           NaN          NaN            NaN
13.000000                           NaN          NaN            NaN
14.000000                           NaN          NaN            NaN
15.000000                           NaN          NaN            NaN
16.000000                           NaN          NaN            NaN
17.000000                           NaN          NaN            NaN
18.000000                           NaN          NaN            NaN
19.000000                           NaN          NaN            NaN
20.000000                           NaN          NaN            NaN
21.000000                           NaN          NaN            NaN
22.000000                           NaN          NaN            NaN
23.000000                           NaN          NaN            NaN
24.000000                           NaN          NaN            NaN
30.000000                           NaN          NaN            NaN
31.000000                           NaN          NaN            NaN
32.000000                           NaN          NaN            NaN
36.000000                           NaN          NaN            NaN
57.000000                           NaN          NaN            NaN
...                                 ...          ...            ...
2124.751823                         NaN          NaN            NaN
5919.439189                         NaN          NaN            NaN
2104.205919                         NaN          NaN            NaN
32426.647329                        NaN          NaN            NaN
3716.369553                         NaN          NaN            NaN